# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-29 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180121_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profilePic',
            field=models.ImageField(default='C:/webpages/static/icons_/account_icon.PNG', upload_to=''),
        ),
    ]
