# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-03 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180129_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profilePic',
            field=models.ImageField(default='/webpages/static/icons_/account_icon.PNG', upload_to=''),
        ),
    ]
