# Generated by Django 2.0.1 on 2018-01-17 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListofChats',
            fields=[
                ('chatID', models.AutoField(primary_key=True, serialize=False)),
                ('className', models.CharField(max_length=30)),
                ('professor', models.CharField(max_length=30)),
                ('s_year', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='MessagesInAChat',
            fields=[
                ('messageID', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=30)),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
                ('important', models.BooleanField(default=False)),
                ('flag', models.BooleanField(default=False)),
                ('rating', models.IntegerField(default=0)),
                ('chatID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webpages.ListofChats')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30)),
                ('university', models.CharField(max_length=30)),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User_s_Chats',
            fields=[
                ('uscID', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=False)),
                ('mutedStatus', models.BooleanField(default=False)),
                ('username', models.CharField(max_length=30)),
                ('chatID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webpages.ListofChats')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webpages.User')),
            ],
        ),
        migrations.AddField(
            model_name='messagesinachat',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webpages.User'),
        ),
    ]
