# Generated by Django 2.0.1 on 2018-01-17 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listofchats',
            options={'verbose_name_plural': 'List of Chats'},
        ),
        migrations.AlterModelOptions(
            name='messagesinachat',
            options={'verbose_name_plural': 'Messages In A Chat'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='user_s_chats',
            options={'verbose_name_plural': "User's Chats"},
        ),
    ]
