# Generated by Django 2.0.1 on 2018-01-17 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0002_auto_20180117_0354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_s_chats',
            name='username',
        ),
    ]
