# Generated by Django 2.0.1 on 2018-01-17 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0003_remove_user_s_chats_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagesinachat',
            name='message',
            field=models.CharField(max_length=100),
        ),
    ]
