# Generated by Django 2.0.1 on 2018-01-19 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0006_auto_20180119_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='memberSince',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='year_in_school',
            field=models.CharField(choices=[('Freshman', 'Freshman'), ('Sophomore', 'Sophomore'), ('Junior', 'Junior'), ('Senior', 'Senior')], default='Freshman', max_length=15),
        ),
    ]
