# Generated by Django 2.0.1 on 2018-01-20 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0008_user_numberoflikes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='USSALEXISTEXS@PORNHUB.COM', max_length=254),
        ),
    ]
