# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-21 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0009_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profilePic',
            field=models.ImageField(default='C:/webpages/static/icons_/account_icon.PNG', upload_to=''),
        ),
    ]
