# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-21 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0010_auto_20180121_0514'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_s_chats',
            old_name='userID',
            new_name='owner',
        ),
        migrations.AlterField(
            model_name='user',
            name='profilePic',
            field=models.ImageField(default='/webpages/static/icons_/account_icon.PNG', upload_to=''),
        ),
    ]
