# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-21 22:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0012_auto_20180121_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagesinachat',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webpages.User'),
        ),
    ]
