# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-01 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0014_auto_20180129_0718'),
    ]

    operations = [
        migrations.AddField(
            model_name='listofchats',
            name='currently_active',
            field=models.BooleanField(default=0),
        ),
    ]
