# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-02 17:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0015_listofchats_currently_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_s_chats',
            old_name='status',
            new_name='seen',
        ),
    ]
