# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-13 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0018_listofchats_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='listofchats',
            name='subject',
            field=models.CharField(default='CS', max_length=5),
            preserve_default=False,
        ),
    ]
